#!/bin/bash

# This script updates the lists of items by translation language.

python get_property_list.py -property:13 -show:label > lists/it.txt
python get_property_list.py -property:11 -show:label > lists/en.txt
python get_property_list.py -property:12 -show:label > lists/de.txt
python get_property_list.py -property:14 -show:label > lists/es.txt
python get_property_list.py -property:15 -show:label > lists/fr.txt
python get_property_list.py -property:16 -show:label > lists/el.txt
python get_property_list.py -property:17 -show:label > lists/ru.txt
python get_property_list.py -property:18 -show:label > lists/si.txt
python get_property_list.py -property:19 -show:label > lists/hu.txt
python get_property_list.py -property:20 -show:label > lists/ro.txt